// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApp.Data;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250729113057_more")]
    partial class more
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.Affiliation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.ToTable("Affiliations", (string)null);
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.Bolster", b =>
                {
                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ExtendedUntil")
                        .HasColumnType("date");

                    b.Property<int?>("ServiceLifeYears")
                        .HasColumnType("integer");

                    b.HasKey("PartId");

                    b.ToTable("Bolsters");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.Coupler", b =>
                {
                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.HasKey("PartId");

                    b.ToTable("Couplers");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.Depot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Depots");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("Code");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CreatorId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ShortName");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers", (string)null);
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.MilageCistern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("CisternId")
                        .HasColumnType("uuid")
                        .HasColumnName("CisternId");

                    b.Property<string>("CisternNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CisternNumber");

                    b.Property<DateOnly>("InputDate")
                        .HasColumnType("date")
                        .HasColumnName("InputDate");

                    b.Property<int>("InputModeCode")
                        .HasColumnType("integer")
                        .HasColumnName("InputModeCode");

                    b.Property<int>("Milage")
                        .HasColumnType("integer")
                        .HasColumnName("Milage");

                    b.Property<int>("MilageNorm")
                        .HasColumnType("integer")
                        .HasColumnName("MilageNorm");

                    b.Property<DateOnly>("RepairDate")
                        .HasColumnType("date")
                        .HasColumnName("RepairDate");

                    b.Property<Guid>("RepairTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("RepairTypeId");

                    b.HasKey("Id");

                    b.HasIndex("CisternId");

                    b.HasIndex("RepairTypeId");

                    b.ToTable("MilageCisterns", (string)null);
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Address");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CreatorId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ShortName");

                    b.Property<bool>("TreatRepairs")
                        .HasColumnType("boolean")
                        .HasColumnName("TreatRepairs");

                    b.Property<string>("UNP")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UNP");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Owners", (string)null);
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.Part", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentLocation")
                        .HasColumnType("text");

                    b.Property<Guid?>("DepotId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ManufactureYear")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PartType")
                        .HasColumnType("integer");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("StampNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepotId");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.PartInstallation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FromLocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("InstalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InstalledBy")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RemovedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("ToLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WagonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FromLocationId");

                    b.HasIndex("PartId");

                    b.HasIndex("ToLocationId");

                    b.HasIndex("WagonId");

                    b.ToTable("PartInstallations");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.RailwayCistern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("AffiliationId")
                        .HasColumnType("uuid")
                        .HasColumnName("AffiliationId");

                    b.Property<int>("AxleCount")
                        .HasColumnType("integer")
                        .HasColumnName("AxleCount");

                    b.Property<DateOnly>("BuildDate")
                        .HasColumnType("date")
                        .HasColumnName("BuildDate");

                    b.Property<DateOnly?>("CommissioningDate")
                        .HasColumnType("date")
                        .HasColumnName("CommissioningDate");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CreatorId");

                    b.Property<int>("DangerClass")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("DangerClass");

                    b.Property<decimal?>("FillingVolume")
                        .HasColumnType("numeric")
                        .HasColumnName("FillingVolume");

                    b.Property<decimal?>("InitialTareWeight")
                        .HasColumnType("numeric")
                        .HasColumnName("InitialTareWeight");

                    b.Property<int>("Length")
                        .HasColumnType("integer")
                        .HasColumnName("Length");

                    b.Property<decimal>("LoadCapacity")
                        .HasColumnType("numeric")
                        .HasColumnName("LoadCapacity");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ManufacturerId");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("ModelId");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Notes");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Number");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("Ownerid");

                    b.Property<DateOnly?>("PeriodDepotRepair")
                        .HasColumnType("date")
                        .HasColumnName("PeriodDepotRepair");

                    b.Property<DateOnly?>("PeriodIntermediateTest")
                        .HasColumnType("date")
                        .HasColumnName("PeriodIntermediateTest");

                    b.Property<DateOnly?>("PeriodMajorRepair")
                        .HasColumnType("date")
                        .HasColumnName("PeriodMajorRepair");

                    b.Property<DateOnly?>("PeriodPeriodicTest")
                        .HasColumnType("date")
                        .HasColumnName("PeriodPeriodicTest");

                    b.Property<decimal>("Pressure")
                        .HasColumnType("numeric")
                        .HasColumnName("Pressure");

                    b.Property<string>("Pripiska")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Pripiska");

                    b.Property<DateOnly?>("ReRegistrationDate")
                        .HasColumnType("date")
                        .HasColumnName("ReRegistrationDate");

                    b.Property<Guid?>("RegistrarId")
                        .HasColumnType("uuid")
                        .HasColumnName("RegistrarId");

                    b.Property<DateOnly>("RegistrationDate")
                        .HasColumnType("date")
                        .HasColumnName("RegistrationDate");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RegistrationNumber");

                    b.Property<string>("Rent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Rent");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("SerialNumber");

                    b.Property<int>("ServiceLifeYears")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(40)
                        .HasColumnName("ServiceLifeYears");

                    b.Property<string>("Substance")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("СУГ")
                        .HasColumnName("Substance");

                    b.Property<decimal>("TareWeight")
                        .HasColumnType("numeric")
                        .HasColumnName("TareWeight");

                    b.Property<string>("TechConditions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TechСonditions");

                    b.Property<decimal>("TestPressure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("TestPressure");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("TypeId");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric")
                        .HasColumnName("Volume");

                    b.HasKey("Id");

                    b.HasIndex("AffiliationId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("ModelId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RegistrarId");

                    b.HasIndex("TypeId");

                    b.ToTable("RailwayCisterns", (string)null);
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.Registrar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Registrars");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.Repair", b =>
                {
                    b.Property<Guid>("RepairId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepotId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("NextRepairDate")
                        .HasColumnType("date");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("RepairDate")
                        .HasColumnType("date");

                    b.Property<Guid>("RepairTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("RepairId");

                    b.HasIndex("DepotId");

                    b.HasIndex("PartId");

                    b.HasIndex("RepairTypeId");

                    b.ToTable("Repairs");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.RepairType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("RepairTypes", (string)null);
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.ShockAbsorber", b =>
                {
                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<string>("ManufacturerCode")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("NextRepairDate")
                        .HasColumnType("date");

                    b.Property<int?>("ServiceLifeYears")
                        .HasColumnType("integer");

                    b.HasKey("PartId");

                    b.ToTable("ShockAbsorbers");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.SideFrame", b =>
                {
                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ExtendedUntil")
                        .HasColumnType("date");

                    b.Property<int?>("ServiceLifeYears")
                        .HasColumnType("integer");

                    b.HasKey("PartId");

                    b.ToTable("SideFrames");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.Vessel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RailwayCisternId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("VesselBuildDate")
                        .HasColumnType("date");

                    b.Property<string>("VesselSerialNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RailwayCisternId");

                    b.ToTable("Vessels");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.WagonModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WagonModels");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.WagonType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("0")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.ToTable("WagonTypes", (string)null);
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.WheelPair", b =>
                {
                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ThicknessLeft")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ThicknessRight")
                        .HasColumnType("numeric");

                    b.Property<string>("WheelType")
                        .HasColumnType("text");

                    b.HasKey("PartId");

                    b.ToTable("WheelPairs");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.AbsorberDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("код");

                    b.Property<string>("Field1")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("поле1");

                    b.HasKey("Id");

                    b.ToTable("справочник_поглащаппарат");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.AbsorberDevice1", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("код");

                    b.Property<string>("Field1")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("поле1");

                    b.HasKey("Id");

                    b.ToTable("справочник_поглащаппарат1");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.AbsorberDeviceAccounting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("код");

                    b.Property<string>("FactoryNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("заводномер");

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("дата установки");

                    b.Property<bool>("IsRolledOut")
                        .HasColumnType("boolean")
                        .HasColumnName("выкачен");

                    b.Property<bool>("IsWrittenOff")
                        .HasColumnType("boolean")
                        .HasColumnName("списан");

                    b.Property<int?>("StorageLocation")
                        .HasColumnType("integer")
                        .HasColumnName("хранение");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("тип");

                    b.Property<string>("WagonNumber")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("вагон");

                    b.Property<DateTime?>("Year")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("год");

                    b.HasKey("Id");

                    b.ToTable("справочник_поглащаппарат_учет");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.AirDistributor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("код");

                    b.Property<string>("Field1")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("поле1");

                    b.HasKey("Id");

                    b.ToTable("справочник_воздухораспределители");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.Brake", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("код");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("описание");

                    b.Property<string>("Field1")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("поле1");

                    b.HasKey("Id");

                    b.ToTable("справочник_тормоз");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CargoName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("названиегруза");

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("код");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("наименование");

                    b.Property<double?>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("цена");

                    b.HasKey("Id");

                    b.ToTable("справочник_груз");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("adres");

                    b.Property<string>("ClientName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("klient");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("kod");

                    b.Property<string>("DepotCodeFromTXT")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("коддепоизтхт");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("nomer");

                    b.Property<string>("Repair")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("remont");

                    b.Property<string>("ShortClientName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("krklient");

                    b.Property<string>("UNP")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("unp");

                    b.HasKey("Id");

                    b.ToTable("справочник_клиенты");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short?>("Associated")
                        .HasColumnType("smallint")
                        .HasColumnName("poputnoe");

                    b.Property<string>("ClientName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("klient");

                    b.Property<string>("ContractCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("valuta dogovora");

                    b.Property<string>("ContractName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("dogovor");

                    b.Property<short?>("DailyTurnover")
                        .HasColumnType("smallint")
                        .HasColumnName("oborotsutki");

                    b.Property<short?>("FactTurnover")
                        .HasColumnType("smallint")
                        .HasColumnName("factoborot");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("deystvuet");

                    b.Property<short?>("Lease")
                        .HasColumnType("smallint")
                        .HasColumnName("arenda");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("nomer");

                    b.Property<int?>("Penalty")
                        .HasColumnType("integer")
                        .HasColumnName("straf");

                    b.Property<string>("PenaltyCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("valutast");

                    b.Property<string>("PenaltyType")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("tipstraf");

                    b.HasKey("Id");

                    b.ToTable("справочник_договоры");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.Cost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short?>("Days")
                        .HasColumnType("smallint")
                        .HasColumnName("сутки");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("nomer");

                    b.Property<double?>("SellingPrice")
                        .HasColumnType("double precision")
                        .HasColumnName("отпускнаяцена");

                    b.Property<double?>("SellingPriceEuro")
                        .HasColumnType("double precision")
                        .HasColumnName("отпускнаяценаевро");

                    b.Property<double?>("SellingPriceEuro2")
                        .HasColumnType("double precision")
                        .HasColumnName("отпускнаяценаевро2");

                    b.Property<double?>("SellingPriceEuro3")
                        .HasColumnType("double precision")
                        .HasColumnName("отпускнаяценаевро3");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("единицаизмерения");

                    b.HasKey("Id");

                    b.ToTable("справочник_стоимость");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CountryCode")
                        .HasColumnType("integer")
                        .HasColumnName("кодстанции");

                    b.Property<string>("CountryName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("названиестраны");

                    b.HasKey("Id");

                    b.ToTable("справочник_страны");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.Defect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DefectCode")
                        .HasColumnType("integer")
                        .HasColumnName("коднеисправности");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("наименование");

                    b.Property<Guid?>("ReasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("причина");

                    b.Property<string>("ShortDefect")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("сокрнеисправность");

                    b.HasKey("Id");

                    b.HasIndex("ReasonId");

                    b.ToTable("спрнеисправности");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.DepotReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("сокр");

                    b.Property<double>("EnterpriseCode")
                        .HasColumnType("double precision")
                        .HasColumnName("кодпредприятия");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("наименование");

                    b.HasKey("Id");

                    b.ToTable("спрдепо");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EmployeeName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("rabotnik");

                    b.Property<string>("EmployeeStationNumber")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("стном");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("nomer");

                    b.Property<string>("Position")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("dolznost");

                    b.HasKey("Id");

                    b.ToTable("справочник_работники");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.EuroCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short?>("Days")
                        .HasColumnType("smallint")
                        .HasColumnName("сутки");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("nomer");

                    b.Property<double?>("SellingPrice")
                        .HasColumnType("double precision")
                        .HasColumnName("отпускнаяцена");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("единицаизмерения");

                    b.HasKey("Id");

                    b.ToTable("справочник_стоимостьевро");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.Fault", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("код");

                    b.Property<string>("FaultCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("код неисправности");

                    b.Property<string>("Note")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("примечание");

                    b.HasKey("Id");

                    b.ToTable("справочник_неисправности");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.GasContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("klient");

                    b.Property<string>("ContractName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("dogovor");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("nomer");

                    b.HasKey("Id");

                    b.ToTable("справочник_договоры_газ");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.ModelVC", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("код");

                    b.Property<string>("Field1")
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("поле1");

                    b.Property<double?>("Field2")
                        .HasColumnType("double precision")
                        .HasColumnName("поле2");

                    b.Property<double?>("Field3")
                        .HasColumnType("double precision")
                        .HasColumnName("поле3");

                    b.Property<int?>("Field4")
                        .HasColumnType("integer")
                        .HasColumnName("поле4");

                    b.Property<double?>("Field5")
                        .HasColumnType("double precision")
                        .HasColumnName("поле5");

                    b.HasKey("Id");

                    b.ToTable("справочник_модельвц");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.Modernization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("ModernizationCode")
                        .HasColumnType("smallint")
                        .HasColumnName("кодмодернизации");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("наименование");

                    b.HasKey("Id");

                    b.ToTable("спрмодернизация");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.PartReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short?>("Detail")
                        .HasColumnType("smallint")
                        .HasColumnName("деталь");

                    b.Property<short>("PartCode")
                        .HasColumnType("smallint")
                        .HasColumnName("коддетали");

                    b.Property<string>("PartName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("наименованиедетали");

                    b.HasKey("Id");

                    b.ToTable("справочник_детали");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.Railway", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("сокр");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("наименование");

                    b.Property<double>("RailwayCode")
                        .HasColumnType("double precision")
                        .HasColumnName("коддороги");

                    b.HasKey("Id");

                    b.ToTable("спрдороги");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.Reason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("код");

                    b.Property<string>("ReasonName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("причина");

                    b.HasKey("Id");

                    b.ToTable("спрпричины");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.ReferenceStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short?>("AdministrationCode")
                        .HasColumnType("smallint")
                        .HasColumnName("кодадминистрации");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("наименование");

                    b.Property<int>("StationCode")
                        .HasColumnType("integer")
                        .HasColumnName("кодстанции");

                    b.HasKey("Id");

                    b.ToTable("спрстанции");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.RepairReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("сокр");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("наименование");

                    b.Property<short>("RepairCode")
                        .HasColumnType("smallint")
                        .HasColumnName("кодремонта");

                    b.HasKey("Id");

                    b.ToTable("спрремонты");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.RepairTypeReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("код");

                    b.Property<string>("Note")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("примечание");

                    b.Property<string>("RepairTypeName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("видремонта");

                    b.HasKey("Id");

                    b.ToTable("справочник_видыремонта");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.Stamp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("тип");

                    b.HasKey("Id");

                    b.ToTable("справочник_клеймо");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("страна дороги код");

                    b.Property<string>("CountryName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("страна дороги");

                    b.Property<string>("FullName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("полноенаименование");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("действует");

                    b.Property<string>("Railway")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("дорога");

                    b.Property<string>("RailwayName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("дорога наименование");

                    b.Property<string>("RemainingOnTrackM")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("остатоквпутим");

                    b.Property<string>("RemainingOnTrackN")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("остатоквпутин");

                    b.Property<string>("RemainingOnTrackR")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("остатоквпутир");

                    b.Property<string>("RemainingOnTrackV")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("остатоквпутив");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("кодстанции");

                    b.Property<string>("StationName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("названиестанции");

                    b.HasKey("Id");

                    b.ToTable("справочник_станции");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.VCType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("код");

                    b.Property<string>("Type")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("тип");

                    b.HasKey("Id");

                    b.ToTable("справочник_типвц");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.Wagon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Assignment")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("pripiska");

                    b.Property<double?>("Capacity")
                        .HasColumnType("double precision")
                        .HasColumnName("emk_vl");

                    b.Property<string>("CarAbsorberDevice")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("carpoglapar_vl");

                    b.Property<string>("CarAbsorberDeviceAdd")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("carpoglaparadd_vl");

                    b.Property<string>("CarAirDistributor")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("carvizdyx_vl");

                    b.Property<int?>("CarAxleLoad")
                        .HasColumnType("integer")
                        .HasColumnName("carosiling_vl");

                    b.Property<double?>("CarAxles")
                        .HasColumnType("double precision")
                        .HasColumnName("carosi_vl");

                    b.Property<string>("CarBrake")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cartorm_vl");

                    b.Property<string>("CarBrand")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("carmarka_vl");

                    b.Property<DateTime?>("CarConstructionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("carpostr_dt");

                    b.Property<string>("CarDescription")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("car_ds");

                    b.Property<int?>("CarFactoryId")
                        .HasColumnType("integer")
                        .HasColumnName("carzav_id");

                    b.Property<string>("CarFactoryNumberId")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("carzavnom_id");

                    b.Property<string>("CarInventory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("carinv");

                    b.Property<double?>("CarLoadCapacityVol")
                        .HasColumnType("double precision")
                        .HasColumnName("cargryz_vl");

                    b.Property<double?>("CarTareVolume")
                        .HasColumnType("double precision")
                        .HasColumnName("cartara_vl");

                    b.Property<decimal?>("CarTareWeight")
                        .HasColumnType("numeric")
                        .HasColumnName("cartar_vl");

                    b.Property<string>("CarTele")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cartele_vl");

                    b.Property<string>("CarType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("carty_vl");

                    b.Property<int?>("CarUser")
                        .HasColumnType("integer")
                        .HasColumnName("caruser_vl");

                    b.Property<int?>("CarUserAddNorm")
                        .HasColumnType("integer")
                        .HasColumnName("caruseraddnor_vl");

                    b.Property<DateTime?>("CarUserAddNormDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("caruseraddnor_dt");

                    b.Property<string>("CarUserAddNormId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("caruseraddnor_id");

                    b.Property<DateTime?>("CarUserNoticeDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("carusernot_dt");

                    b.Property<DateTime?>("CarUserStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("caruserbeg_dt");

                    b.Property<string>("CarWheelset")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("carkolpat_vl");

                    b.Property<string>("Class")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("класс");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_dt");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("create_us");

                    b.Property<DateTime?>("DataPPE")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datappe");

                    b.Property<string>("DocAuthorId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("docautor_id");

                    b.Property<DateTime?>("DocDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("docdate_dt");

                    b.Property<decimal?>("FillingLevel")
                        .HasColumnType("numeric")
                        .HasColumnName("napol_vl");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("deystvuet");

                    b.Property<bool>("IsLeased")
                        .HasColumnType("boolean")
                        .HasColumnName("arenda");

                    b.Property<double?>("LoadCapacity")
                        .HasColumnType("double precision")
                        .HasColumnName("gruzopodemnost");

                    b.Property<int?>("MileageNorm")
                        .HasColumnType("integer")
                        .HasColumnName("normaprobega");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_dt");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("modified_us");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("nomer");

                    b.Property<double?>("OldCarTareVolume")
                        .HasColumnType("double precision")
                        .HasColumnName("cartara_vl_old");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("vladelec");

                    b.Property<double?>("Pressure")
                        .HasColumnType("double precision")
                        .HasColumnName("давление");

                    b.Property<string>("RailwayCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("koddorogi");

                    b.Property<string>("RegNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("regnom");

                    b.Property<DateTime?>("RegNumberDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("regnom_dt");

                    b.Property<string>("RegNumberOrg")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("regnom_org");

                    b.Property<string>("SUG")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("суг");

                    b.Property<double?>("Tare")
                        .HasColumnType("double precision")
                        .HasColumnName("tara");

                    b.Property<string>("Type")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("tip");

                    b.Property<string>("Way")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("way");

                    b.Property<decimal?>("WeightVolume")
                        .HasColumnType("numeric")
                        .HasColumnName("ves_vl");

                    b.HasKey("Id");

                    b.ToTable("справочник_вагоны");
                });

            modelBuilder.Entity("WebApp.Data.Entities.Users.PermissionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PermissionEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Read"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Create"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Update"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Delete"
                        });
                });

            modelBuilder.Entity("WebApp.Data.Entities.Users.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("WebApp.Data.Entities.Users.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("WebApp.Data.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApp.Data.Entities.Users.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.Bolster", b =>
                {
                    b.HasOne("WebApp.Data.Entities.RailwayCisterns.Part", "Part")
                        .WithOne("Bolster")
                        .HasForeignKey("WebApp.Data.Entities.RailwayCisterns.Bolster", "PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.Coupler", b =>
                {
                    b.HasOne("WebApp.Data.Entities.RailwayCisterns.Part", "Part")
                        .WithOne("Coupler")
                        .HasForeignKey("WebApp.Data.Entities.RailwayCisterns.Coupler", "PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.MilageCistern", b =>
                {
                    b.HasOne("WebApp.Data.Entities.RailwayCisterns.RailwayCistern", "Cistern")
                        .WithMany("MilageCisterns")
                        .HasForeignKey("CisternId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CisternId_RailwayCisterns_id");

                    b.HasOne("WebApp.Data.Entities.RailwayCisterns.RepairType", "RepairType")
                        .WithMany("MilageCisterns")
                        .HasForeignKey("RepairTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_RepairTypeId_RepairTypes_id");

                    b.Navigation("Cistern");

                    b.Navigation("RepairType");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.Part", b =>
                {
                    b.HasOne("WebApp.Data.Entities.RailwayCisterns.Depot", "Depot")
                        .WithMany("Parts")
                        .HasForeignKey("DepotId");

                    b.Navigation("Depot");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.PartInstallation", b =>
                {
                    b.HasOne("WebApp.Data.Entities.RailwayCisterns.Location", "FromLocation")
                        .WithMany("FromInstallations")
                        .HasForeignKey("FromLocationId");

                    b.HasOne("WebApp.Data.Entities.RailwayCisterns.Part", "Part")
                        .WithMany("PartInstallations")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Data.Entities.RailwayCisterns.Location", "ToLocation")
                        .WithMany("ToInstallations")
                        .HasForeignKey("ToLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Data.Entities.RailwayCisterns.RailwayCistern", "Wagon")
                        .WithMany("PartInstallations")
                        .HasForeignKey("WagonId");

                    b.Navigation("FromLocation");

                    b.Navigation("Part");

                    b.Navigation("ToLocation");

                    b.Navigation("Wagon");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.RailwayCistern", b =>
                {
                    b.HasOne("WebApp.Data.Entities.RailwayCisterns.Affiliation", "Affiliation")
                        .WithMany("RailwayCisterns")
                        .HasForeignKey("AffiliationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_RailwayCisterns_Affiliations_AffiliationId");

                    b.HasOne("WebApp.Data.Entities.RailwayCisterns.Manufacturer", "Manufacturer")
                        .WithMany("RailwayCisterns")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RailwayCisterns_Manufacturers_ManufacturerId");

                    b.HasOne("WebApp.Data.Entities.RailwayCisterns.WagonModel", "Model")
                        .WithMany("RailwayCisterns")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_RailwayCisterns_WagonModels_ModelId");

                    b.HasOne("WebApp.Data.Entities.RailwayCisterns.Owner", "Owner")
                        .WithMany("RailwayCisterns")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_RailwayCisterns_Owners_Ownerid");

                    b.HasOne("WebApp.Data.Entities.RailwayCisterns.Registrar", "Registrar")
                        .WithMany("RailwayCisterns")
                        .HasForeignKey("RegistrarId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_RailwayCisterns_Registrars_RegistrarId");

                    b.HasOne("WebApp.Data.Entities.RailwayCisterns.WagonType", "Type")
                        .WithMany("RailwayCisterns")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RailwayCisterns_WagonTypes_TypeId");

                    b.Navigation("Affiliation");

                    b.Navigation("Manufacturer");

                    b.Navigation("Model");

                    b.Navigation("Owner");

                    b.Navigation("Registrar");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.Repair", b =>
                {
                    b.HasOne("WebApp.Data.Entities.RailwayCisterns.Depot", "Depot")
                        .WithMany("Repairs")
                        .HasForeignKey("DepotId");

                    b.HasOne("WebApp.Data.Entities.RailwayCisterns.Part", "Part")
                        .WithMany("Repairs")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Data.Entities.RailwayCisterns.RepairType", "RepairType")
                        .WithMany("Repairs")
                        .HasForeignKey("RepairTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Depot");

                    b.Navigation("Part");

                    b.Navigation("RepairType");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.ShockAbsorber", b =>
                {
                    b.HasOne("WebApp.Data.Entities.RailwayCisterns.Part", "Part")
                        .WithOne("ShockAbsorber")
                        .HasForeignKey("WebApp.Data.Entities.RailwayCisterns.ShockAbsorber", "PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.SideFrame", b =>
                {
                    b.HasOne("WebApp.Data.Entities.RailwayCisterns.Part", "Part")
                        .WithOne("SideFrame")
                        .HasForeignKey("WebApp.Data.Entities.RailwayCisterns.SideFrame", "PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.Vessel", b =>
                {
                    b.HasOne("WebApp.Data.Entities.RailwayCisterns.RailwayCistern", "RailwayCistern")
                        .WithMany()
                        .HasForeignKey("RailwayCisternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RailwayCistern");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.WheelPair", b =>
                {
                    b.HasOne("WebApp.Data.Entities.RailwayCisterns.Part", "Part")
                        .WithOne("WheelPair")
                        .HasForeignKey("WebApp.Data.Entities.RailwayCisterns.WheelPair", "PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.Defect", b =>
                {
                    b.HasOne("WebApp.Data.Entities.References.Reason", "Reason")
                        .WithMany("Defects")
                        .HasForeignKey("ReasonId");

                    b.Navigation("Reason");
                });

            modelBuilder.Entity("WebApp.Data.Entities.Users.RolePermission", b =>
                {
                    b.HasOne("WebApp.Data.Entities.Users.PermissionEntity", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Data.Entities.Users.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.Data.Entities.Users.UserRole", b =>
                {
                    b.HasOne("WebApp.Data.Entities.Users.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Data.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.Affiliation", b =>
                {
                    b.Navigation("RailwayCisterns");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.Depot", b =>
                {
                    b.Navigation("Parts");

                    b.Navigation("Repairs");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.Location", b =>
                {
                    b.Navigation("FromInstallations");

                    b.Navigation("ToInstallations");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.Manufacturer", b =>
                {
                    b.Navigation("RailwayCisterns");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.Owner", b =>
                {
                    b.Navigation("RailwayCisterns");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.Part", b =>
                {
                    b.Navigation("Bolster");

                    b.Navigation("Coupler");

                    b.Navigation("PartInstallations");

                    b.Navigation("Repairs");

                    b.Navigation("ShockAbsorber");

                    b.Navigation("SideFrame");

                    b.Navigation("WheelPair");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.RailwayCistern", b =>
                {
                    b.Navigation("MilageCisterns");

                    b.Navigation("PartInstallations");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.Registrar", b =>
                {
                    b.Navigation("RailwayCisterns");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.RepairType", b =>
                {
                    b.Navigation("MilageCisterns");

                    b.Navigation("Repairs");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.WagonModel", b =>
                {
                    b.Navigation("RailwayCisterns");
                });

            modelBuilder.Entity("WebApp.Data.Entities.RailwayCisterns.WagonType", b =>
                {
                    b.Navigation("RailwayCisterns");
                });

            modelBuilder.Entity("WebApp.Data.Entities.References.Reason", b =>
                {
                    b.Navigation("Defects");
                });
#pragma warning restore 612, 618
        }
    }
}
