import { FilterFieldConfig, FilterOperator, FilterDataType } from '@/types/filters';

export const cisternFilterConfig: FilterFieldConfig[] = [
  {
    field: 'number',
    label: 'Номер',
    dataType: FilterDataType.STRING,
    operators: [
      FilterOperator.EQUALS,
      FilterOperator.NOT_EQUALS,
      FilterOperator.CONTAINS,
      FilterOperator.NOT_CONTAINS,
      FilterOperator.STARTS_WITH,
      FilterOperator.ENDS_WITH,
    ],
    component: 'input',
  },
  {
    field: 'serialNumber',
    label: 'Серийный номер',
    dataType: FilterDataType.STRING,
    operators: [
      FilterOperator.EQUALS,
      FilterOperator.NOT_EQUALS,
      FilterOperator.CONTAINS,
      FilterOperator.NOT_CONTAINS,
    ],
    component: 'input',
  },
  {
    field: 'manufacturerName',
    label: 'Производитель',
    dataType: FilterDataType.STRING,
    operators: [
      FilterOperator.EQUALS,
      FilterOperator.NOT_EQUALS,
      FilterOperator.CONTAINS,
      FilterOperator.NOT_CONTAINS,
    ],
    component: 'input',
  },
  {
    field: 'typeName',
    label: 'Тип',
    dataType: FilterDataType.STRING,
    operators: [
      FilterOperator.EQUALS,
      FilterOperator.NOT_EQUALS,
      FilterOperator.CONTAINS,
      FilterOperator.NOT_CONTAINS,
    ],
    component: 'input',
  },
  {
    field: 'modelName',
    label: 'Модель',
    dataType: FilterDataType.STRING,
    operators: [
      FilterOperator.EQUALS,
      FilterOperator.NOT_EQUALS,
      FilterOperator.CONTAINS,
      FilterOperator.NOT_CONTAINS,
      FilterOperator.IS_NULL,
      FilterOperator.IS_NOT_NULL,
    ],
    component: 'input',
  },
  {
    field: 'tareWeight',
    label: 'Тара (кг)',
    dataType: FilterDataType.NUMBER,
    operators: [
      FilterOperator.EQUALS,
      FilterOperator.NOT_EQUALS,
      FilterOperator.GREATER_THAN,
      FilterOperator.GREATER_THAN_OR_EQUAL,
      FilterOperator.LESS_THAN,
      FilterOperator.LESS_THAN_OR_EQUAL,
      FilterOperator.BETWEEN,
    ],
    component: 'input',
  },
  {
    field: 'loadCapacity',
    label: 'Грузоподъемность (кг)',
    dataType: FilterDataType.NUMBER,
    operators: [
      FilterOperator.EQUALS,
      FilterOperator.NOT_EQUALS,
      FilterOperator.GREATER_THAN,
      FilterOperator.GREATER_THAN_OR_EQUAL,
      FilterOperator.LESS_THAN,
      FilterOperator.LESS_THAN_OR_EQUAL,
      FilterOperator.BETWEEN,
    ],
    component: 'input',
  },
  {
    field: 'volume',
    label: 'Объем (м³)',
    dataType: FilterDataType.NUMBER,
    operators: [
      FilterOperator.EQUALS,
      FilterOperator.NOT_EQUALS,
      FilterOperator.GREATER_THAN,
      FilterOperator.GREATER_THAN_OR_EQUAL,
      FilterOperator.LESS_THAN,
      FilterOperator.LESS_THAN_OR_EQUAL,
      FilterOperator.BETWEEN,
    ],
    component: 'input',
  },
  {
    field: 'buildDate',
    label: 'Дата постройки',
    dataType: FilterDataType.DATE,
    operators: [
      FilterOperator.EQUALS,
      FilterOperator.NOT_EQUALS,
      FilterOperator.GREATER_THAN,
      FilterOperator.GREATER_THAN_OR_EQUAL,
      FilterOperator.LESS_THAN,
      FilterOperator.LESS_THAN_OR_EQUAL,
      FilterOperator.BETWEEN,
    ],
    component: 'date',
  },
  {
    field: 'registrationDate',
    label: 'Дата регистрации',
    dataType: FilterDataType.DATE,
    operators: [
      FilterOperator.EQUALS,
      FilterOperator.NOT_EQUALS,
      FilterOperator.GREATER_THAN,
      FilterOperator.GREATER_THAN_OR_EQUAL,
      FilterOperator.LESS_THAN,
      FilterOperator.LESS_THAN_OR_EQUAL,
      FilterOperator.BETWEEN,
    ],
    component: 'date',
  },
  {
    field: 'ownerName',
    label: 'Собственник',
    dataType: FilterDataType.STRING,
    operators: [
      FilterOperator.EQUALS,
      FilterOperator.NOT_EQUALS,
      FilterOperator.CONTAINS,
      FilterOperator.NOT_CONTAINS,
      FilterOperator.IS_NULL,
      FilterOperator.IS_NOT_NULL,
    ],
    component: 'input',
  },
  {
    field: 'registrarName',
    label: 'Регистратор',
    dataType: FilterDataType.STRING,
    operators: [
      FilterOperator.EQUALS,
      FilterOperator.NOT_EQUALS,
      FilterOperator.CONTAINS,
      FilterOperator.NOT_CONTAINS,
      FilterOperator.IS_NULL,
      FilterOperator.IS_NOT_NULL,
    ],
    component: 'input',
  },
  {
    field: 'axleCount',
    label: 'Количество осей',
    dataType: FilterDataType.NUMBER,
    operators: [
      FilterOperator.EQUALS,
      FilterOperator.NOT_EQUALS,
      FilterOperator.GREATER_THAN,
      FilterOperator.GREATER_THAN_OR_EQUAL,
      FilterOperator.LESS_THAN,
      FilterOperator.LESS_THAN_OR_EQUAL,
    ],
    component: 'input',
  },
  {
    field: 'pressure',
    label: 'Давление',
    dataType: FilterDataType.NUMBER,
    operators: [
      FilterOperator.EQUALS,
      FilterOperator.NOT_EQUALS,
      FilterOperator.GREATER_THAN,
      FilterOperator.GREATER_THAN_OR_EQUAL,
      FilterOperator.LESS_THAN,
      FilterOperator.LESS_THAN_OR_EQUAL,
      FilterOperator.BETWEEN,
    ],
    component: 'input',
  },
  {
    field: 'dangerClass',
    label: 'Класс опасности',
    dataType: FilterDataType.NUMBER,
    operators: [
      FilterOperator.EQUALS,
      FilterOperator.NOT_EQUALS,
      FilterOperator.IN,
    ],
    component: 'input',
  },
  {
    field: 'substance',
    label: 'Вещество',
    dataType: FilterDataType.STRING,
    operators: [
      FilterOperator.EQUALS,
      FilterOperator.NOT_EQUALS,
      FilterOperator.CONTAINS,
      FilterOperator.NOT_CONTAINS,
    ],
    component: 'input',
  },
];

// Конфигурации для справочников
export const manufacturerFilterConfig: FilterFieldConfig[] = [
  {
    field: 'name',
    label: 'Название',
    dataType: FilterDataType.STRING,
    operators: [
      FilterOperator.EQUALS,
      FilterOperator.NOT_EQUALS,
      FilterOperator.CONTAINS,
      FilterOperator.NOT_CONTAINS,
      FilterOperator.STARTS_WITH,
      FilterOperator.ENDS_WITH,
    ],
    component: 'input',
  },
  {
    field: 'country',
    label: 'Страна',
    dataType: FilterDataType.STRING,
    operators: [
      FilterOperator.EQUALS,
      FilterOperator.NOT_EQUALS,
      FilterOperator.CONTAINS,
      FilterOperator.NOT_CONTAINS,
      FilterOperator.IS_NULL,
      FilterOperator.IS_NOT_NULL,
    ],
    component: 'input',
  },
  {
    field: 'createdAt',
    label: 'Дата создания',
    dataType: FilterDataType.DATE,
    operators: [
      FilterOperator.EQUALS,
      FilterOperator.GREATER_THAN,
      FilterOperator.GREATER_THAN_OR_EQUAL,
      FilterOperator.LESS_THAN,
      FilterOperator.LESS_THAN_OR_EQUAL,
      FilterOperator.BETWEEN,
    ],
    component: 'date',
  },
];

export const wagonTypeFilterConfig: FilterFieldConfig[] = [
  {
    field: 'name',
    label: 'Название',
    dataType: FilterDataType.STRING,
    operators: [
      FilterOperator.EQUALS,
      FilterOperator.NOT_EQUALS,
      FilterOperator.CONTAINS,
      FilterOperator.NOT_CONTAINS,
      FilterOperator.STARTS_WITH,
      FilterOperator.ENDS_WITH,
    ],
    component: 'input',
  },
  {
    field: 'description',
    label: 'Описание',
    dataType: FilterDataType.STRING,
    operators: [
      FilterOperator.CONTAINS,
      FilterOperator.NOT_CONTAINS,
      FilterOperator.IS_NULL,
      FilterOperator.IS_NOT_NULL,
    ],
    component: 'input',
  },
];

export const wagonModelFilterConfig: FilterFieldConfig[] = [
  {
    field: 'name',
    label: 'Название',
    dataType: FilterDataType.STRING,
    operators: [
      FilterOperator.EQUALS,
      FilterOperator.NOT_EQUALS,
      FilterOperator.CONTAINS,
      FilterOperator.NOT_CONTAINS,
      FilterOperator.STARTS_WITH,
      FilterOperator.ENDS_WITH,
    ],
    component: 'input',
  },
  {
    field: 'description',
    label: 'Описание',
    dataType: FilterDataType.STRING,
    operators: [
      FilterOperator.CONTAINS,
      FilterOperator.NOT_CONTAINS,
      FilterOperator.IS_NULL,
      FilterOperator.IS_NOT_NULL,
    ],
    component: 'input',
  },
];

// Базовая конфигурация для справочников с названием и описанием
export const basicReferenceFilterConfig: FilterFieldConfig[] = [
  {
    field: 'name',
    label: 'Название',
    dataType: FilterDataType.STRING,
    operators: [
      FilterOperator.EQUALS,
      FilterOperator.NOT_EQUALS,
      FilterOperator.CONTAINS,
      FilterOperator.NOT_CONTAINS,
      FilterOperator.STARTS_WITH,
      FilterOperator.ENDS_WITH,
    ],
    component: 'input',
  },
  {
    field: 'description',
    label: 'Описание',
    dataType: FilterDataType.STRING,
    operators: [
      FilterOperator.CONTAINS,
      FilterOperator.NOT_CONTAINS,
      FilterOperator.IS_NULL,
      FilterOperator.IS_NOT_NULL,
    ],
    component: 'input',
  },
  {
    field: 'createdAt',
    label: 'Дата создания',
    dataType: FilterDataType.DATE,
    operators: [
      FilterOperator.EQUALS,
      FilterOperator.GREATER_THAN,
      FilterOperator.GREATER_THAN_OR_EQUAL,
      FilterOperator.LESS_THAN,
      FilterOperator.LESS_THAN_OR_EQUAL,
      FilterOperator.BETWEEN,
    ],
    component: 'date',
  },
];
